id: P006821
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ74375
  title: དེབ་ཐེར་སྔོན་པོ།
  author: ''
  volumes:
    751d3d212c434db192d683af58af3b6d:
      image_group_id: I4CZ74377
      title: ''
      volume_number: 1
      total_pages: 972
