id: P006821
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 12:24:51.609695
source_metadata:
  id: bdr:W4CZ74375
  title: དེབ་ཐེར་སྔོན་པོ།
  author: ''
  volumes:
    751d3d212c434db192d683af58af3b6d:
      image_group_id: I4CZ74377
      title: ''
      volume_number: 1
      total_pages: 972
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
